//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyDescription("Create script install package from script install template and msi or exe file")]
[assembly: AssemblyCompany("github.trondr")]
[assembly: AssemblyProduct("Script.Install.Creator.Gui")]
[assembly: AssemblyCopyright("Copyright © github.trondr 2016")]
[assembly: CLSCompliant(false)]
[assembly: AssemblyInformationalVersion("1.0.16089.0.87be476")]
[assembly: AssemblyVersion("1.0.16089.0")]
[assembly: AssemblyFileVersion("1.0.16089.0")]


